/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vound.intella.scripting.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-10-26")
public enum Action implements org.apache.thrift.TEnum {
  /**
   * Include and process the item and all of its descendants.
   */
  Include(0),
  /**
   * Skip processing this item and all of its descendants/children.
   */
  Skip(1),
  /**
   * Stub the item. Descendants/children will be processed.
   */
  Stub(2);

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Action findByValue(int value) { 
    switch (value) {
      case 0:
        return Include;
      case 1:
        return Skip;
      case 2:
        return Stub;
      default:
        return null;
    }
  }
}
